### ISSUE TITLE
Auto generated link at the end of the README is duplicated

### ISSUE THREAD

**Issue by PeterBell** [learn-co-curriculum/activerecord-associations-intro#12]
This may be one for @pletcher but cc @AnnJohn - If you view the README you'll see two links at the very bottom of the readme. I'd like to remove one, but both are auto generated and don't show up when I try to edit the README. Any thoughts on how to resolve this? It appears to be an issue some times when a ∂ to a README gets merged in. Any input appreciated. Sorry for all the questions, but the good news is that once I start to understand these things I can knock them out myself!

**Comment by pletcher** [comment]
I'll have to look into how these are generated, but I was able to remove this one (for now -- cue ominous music). Hopefully it doesn't come back, but lemme know if it does!
