### ISSUE TITLE
Migration snippets should specify version

### ISSUE THREAD

**Issue by kwebster2** [learn-co-curriculum/activerecord-associations-intro#22]
@cernanb 
The codealong as written will result in errors. No version is specified for ActiveRecord in the Gemfile, so the latest version, which requires specifying the Rails version for which the migrations are intended, is used. The code snippets for the migrations in the README do not specify a version.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for bringing this to our attention. We added the `ActiveRecord::Migration` version declaration to the README and migrations.

As always thank you for contributing!
