### ISSUE TITLE
ActiveRecord Associations Video Review

### ISSUE THREAD

**Issue by Samoth112** [learn-co-curriculum/activerecord-associations-intro#23]
In Ari's lecture for the above mentioned lesson, from 18:45 to about 24:45, he sets "runaway.artist = kanye" then calls "kanye.songs" and the song runaway is indeed included in the collection. However, in this lesson, it says that this simply will not work, and that in order for "adele.songs", the example given toward the bottom of the page, to be populated, we have to first << the song into adele.songs. After speaking with one of the technical coaches, it seems that the difference here is that Ari calls .save and .create, which this lesson does not. If this is indeed the reason for this discrepancy, I think that distinction should be called out here or in Ari's lecture video or both.

**Comment by maxwellbenton** [comment]
Hi @Samoth112,

Thank you for spotting this and providing feedback. I was able to take a look at the video content and it does seem like there is a bit missing that may have been previously cut out. Neither `save` nor `create` will allow for the Artist class (the 'has_many' side of the AR relationship) to update if a Song instance is assigned an artist.

I've documented this as a known issue. We are in the process of reworking our Ruby and Rails content and will address this in an upcoming update. 

Thank you for contributing to a learn.co lesson!

**Comment by maxwellbenton** [comment]
Hi @Samoth112,

The content of this lesson has been updated to better align with the video and now includes clearer information about using save and how AR behaves differently depending on which side of an association you update (and save).

Thank you for contributing to a learn.co lesson!
