### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by ytsuji27** [learn-co-curriculum/activerecord-associations-intro#25]
At the end of the lab, it goes through associating the song "Rolling in the Deep" to the artist "Adele" and to the genre "Pop". However, this does not update the "artist_id" and "genre_id" of the song object "Rolling in the Deep". I would suggest to include that running .save after each of these would result in those references getting updated.

Thanks

**Comment by maxwellbenton** [comment]
Hi @ytsuji27,

Thank you for opening this issue and providing feedback. We've updated this instructions in this lesson to talk more about the use of `save` as well as clarified and corrected the ending content. With these updates, the references should now appear as students are following along, and this should resolve the issue and help prevent future confusion.

Thank you for contributing to a Learn lesson!
