### ISSUE TITLE
minor fix

### ISSUE THREAD

**Issue by LindaHaviv** [learn-co-curriculum/activerecord-associations-intro#5]
just want to help out so it's not as confusing for future students. Add a song.rb file to the one we clone for this lab because the file I cloned has some files that we need to add and some that we don't. The instructions indicate that we need to create them but the fact that some of these files are already created and some aren't in the models folder for example is a little confusing for some. 

I saw a few fellow peers of mine get confused and for learn verified students who may not have people who can reassure/help sitting next to them it may be helpful. I know this is open source so I will probably just send an issue any time I see something that may confuse some people.

**Comment by AnnJohn** [comment]
should be fixed. thanks for raising the issue @LindaHaviv
